name: Deploy to Lambda

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.ROLE_ARN }}
        role-session-name: 'oidc-lambda'
    - name: "Verify connection"
      run: |
        aws sts get-caller-identity
        
