name: Deploy Serverless App

on:
  workflow_dispatch:
  pull_request:

env:
  REGION: ${{ secrets.AWS_REGION }}
  BUCKET: ${{ secrets.S3_BUCKET }}

permissions:
      id-token: write
      contents: read

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.13
    - name: Setup AWS SAM CLI
      uses: aws-actions/setup-sam@v2
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.ROLE_ARN }}
        role-session-name: 'oidc-lambda'
    - name: "Build and validate app"
      env:
          REGION: ${{ secrets.AWS_REGION }}
          BUCKET: ${{ secrets.S3_BUCKET }}
      run: |
        sam build --use-container
        sam validate
